name: safety_app
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_credit_card: ^4.1.0
  cupertino_icons: ^1.0.8
  animate_do: ^5.1.0
  build_runner: ^2.14.1
  dio: ^5.9.2
  dotted_border: ^3.1.0
  flutter_native_splash: ^2.4.7
  flutter_screenutil: ^5.9.3
  google_fonts: ^8.0.2
  flutter_svg: ^2.0.10

  # location & maps
  geocoding: ^4.0.0
  geolocator: ^14.0.2
  google_maps_flutter: ^2.17.0

  # state & DI
  get_it: ^9.2.1

  # networking & models
  json_annotation: ^4.11.0
  json_serializable: ^6.13.1
  retrofit_generator: ^10.2.5

  # local storage & UI
  shared_preferences: ^2.5.5
  smooth_page_indicator: ^2.0.1
  image_picker: ^1.1.2
  file_picker: ^8.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_bloc: ^9.1.1
  equatable: ^2.0.8
  flutter_map: ^8.3.0
  latlong2: ^0.9.1
  location: ^8.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/